language: python


env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"


install:
  - pip install tox
  - pip install .
  - pip install requirements.txt
  - pip install test-requirements.txt


script:
  - tox
